#!/usr/bin/env python
"""Re-run scripts/evaluate.py on the 18 main checkpoints and save JSONs.

This is needed because the historical
``outputs/evaluations/<dataset>_<method>_seed<n>_test.json`` files were
generated by a now-removed recovery pipeline before ``boundary_f1`` was
corrected (the disjoint-but-both-nonempty case used to return 1.0 instead of
0.0). DSC, IoU, HD95, and ASSD reproduce exactly from the saved prediction
arrays, but BF1 needs to be regenerated with the patched metric.

Output schema matches what ``per_image_paired_analysis.py`` and
the evaluation outputs already expect.
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import numpy as np
import torch
from torch.utils.data import DataLoader

from bds_lite.data import NpzSegmentationDataset
from bds_lite.data.boundary import mask_to_boundary
from bds_lite.evaluation.metrics import assd, boundary_f1, dice_score, hd95, iou_score
from bds_lite.training import build_model
from bds_lite.training.runner import inference_forward, move_batch_to_device
from bds_lite.utils import seed_everything


def _patch_legacy_config(config: dict) -> dict:
    """Map historical model.name='bds_lite' and 'use_boundary_gate' to current keys."""
    cfg = copy.deepcopy(config)
    model_cfg = cfg.get("model", {})
    if model_cfg.get("name") == "bds_lite":
        model_cfg["name"] = "bdslite_unet"
        if "use_boundary_gate" in model_cfg and "boundary_gate" not in model_cfg:
            model_cfg["boundary_gate"] = model_cfg["use_boundary_gate"]
    cfg["model"] = model_cfg
    return cfg


def _rename_legacy_keys(state_dict: dict) -> dict:
    renamed = {}
    for k, v in state_dict.items():
        new_k = (
            k.replace("projection_head.", "seg_to_boundary_feature.", 1)
            if k.startswith("projection_head.")
            else k
        )
        renamed[new_k] = v
    return renamed


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "outputs" / "evaluations"
PRED_DIR = ROOT / "outputs" / "evaluations" / "predictions"

SAVE_PREDICTIONS = True  # write per-image .npy alongside JSONs

# Dataset → eval-split mapping used by the historical pipeline.
DATASET_SPLIT = {
    "isic2018": "val",  # no test partition; historical "test" JSON used val predictions
    "acdc": "test",
    "synapse": "test",
}

CHECKPOINTS = []
for dataset in ("isic2018", "acdc", "synapse"):
    for method in ("unet", "bds_lite_full", "ege_unet"):
        for seed in (1, 2, 3):
            # Historical U-Net/BDS-Lite checkpoints live under outputs/runs/<exp>/best.pt.
            # Newer training writes to outputs/checkpoints/<exp>/best.pt — accept either.
            candidates = [
                ROOT / f"outputs/runs/{dataset}_{method}_seed{seed}/best.pt",
                ROOT / f"outputs/checkpoints/{dataset}_{method}_seed{seed}/best.pt",
            ]
            for ckpt in candidates:
                if ckpt.exists():
                    CHECKPOINTS.append((dataset, method, seed, ckpt))
                    break


def _nanmean(values) -> float:
    arr = np.asarray(list(values), dtype=np.float64)
    if arr.size == 0 or np.isnan(arr).all():
        return float("nan")
    return float(np.nanmean(arr))


def _nanstd(values) -> float:
    arr = np.asarray(list(values), dtype=np.float64)
    if arr.size == 0 or np.isnan(arr).all():
        return float("nan")
    return float(np.nanstd(arr))


def evaluate(checkpoint: Path, dataset_name: str, split: str, run_name: str | None = None) -> dict:
    payload = torch.load(checkpoint, map_location="cpu", weights_only=False)
    config = _patch_legacy_config(payload["config"])
    seed_everything(int(config["project"].get("seed", 2026)))

    dataset = NpzSegmentationDataset(
        Path(config["dataset"]["processed_dir"]),
        split=split,
        require_boundary=False,
    )
    loader = DataLoader(dataset, batch_size=1, shuffle=False, num_workers=0)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = build_model(config).to(device)
    state_dict = _rename_legacy_keys(payload["model"])
    model.load_state_dict(state_dict)
    model.eval()

    num_classes = int(
        config.get("model", {}).get("num_classes", config.get("dataset", {}).get("num_classes", 2))
    )
    all_labels = list(range(num_classes))
    foreground_labels = list(range(1, num_classes)) if num_classes > 1 else [1]

    per_label = {
        label: {m: [] for m in ("dsc", "iou", "hd95", "assd", "boundary_f1")}
        for label in (all_labels if num_classes > 1 else foreground_labels)
    }

    pred_subdir = None
    if SAVE_PREDICTIONS:
        # Use the explicit run_name (includes seed) when provided so seeds 2/3
        # don't collide with seed 1 on disk.
        folder = run_name or f"{config['experiment']['name']}_{split}"
        pred_subdir = PRED_DIR / folder
        pred_subdir.mkdir(parents=True, exist_ok=True)

    with torch.no_grad():
        for batch in loader:
            batch = move_batch_to_device(batch, device)
            outputs = inference_forward(model, batch["image"])
            pred = outputs["seg_logits"].argmax(dim=1).cpu().numpy()[0]
            target = batch["mask"].cpu().numpy()[0]
            spacing = (
                tuple(batch["spacing"].cpu().numpy()[0].tolist()) if "spacing" in batch else None
            )
            if pred_subdir is not None:
                sample_id = batch["id"][0] if isinstance(batch["id"], list) else str(batch["id"])
                np.save(pred_subdir / f"{sample_id}.npy", pred.astype(np.uint8))
            for label in per_label:
                per_label[label]["dsc"].append(dice_score(pred, target, label))
                per_label[label]["iou"].append(iou_score(pred, target, label))
                per_label[label]["hd95"].append(hd95(pred, target, label, spacing=spacing))
                per_label[label]["assd"].append(assd(pred, target, label, spacing=spacing))
                pred_boundary = mask_to_boundary((pred == label).astype(np.uint8), radius=1)
                target_boundary = mask_to_boundary((target == label).astype(np.uint8), radius=1)
                per_label[label]["boundary_f1"].append(
                    boundary_f1(pred_boundary, target_boundary, tolerance=2)
                )

    metric_results = {}
    for m in ("dsc", "iou", "hd95", "assd", "boundary_f1"):
        # per-class means over images
        class_means = {lbl: _nanmean(per_label[lbl][m]) for lbl in per_label}
        class_stds = {lbl: _nanstd(per_label[lbl][m]) for lbl in per_label}
        # macro (all classes incl. background when multi-class)
        macro_mean = _nanmean(class_means.values())
        macro_std = _nanmean(class_stds.values())
        # foreground macro (mean over foreground class means only)
        fg_mean = _nanmean([class_means[lbl] for lbl in foreground_labels])
        fg_std = _nanmean([class_stds[lbl] for lbl in foreground_labels])
        metric_results[m] = {
            "macro_mean": macro_mean,
            "macro_std": macro_std,
            "foreground_macro_mean": fg_mean,
            "foreground_macro_std": fg_std,
        }

    return {
        "experiment_id": config["experiment"]["name"],
        "split": split,
        "checkpoint": str(checkpoint.relative_to(ROOT)),
        "num_samples": len(dataset),
        "tta": "none",
        "metrics": metric_results,
    }


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for dataset, method, seed, ckpt in CHECKPOINTS:
        split = DATASET_SPLIT[dataset]
        out_name = f"{dataset}_{method}_seed{seed}_test.json"
        out_path = OUT_DIR / out_name
        if not ckpt.exists():
            print(f"  SKIP {out_name}: checkpoint missing")
            continue
        run_name = f"{dataset}_{method}_seed{seed}_{split}"
        result = evaluate(ckpt, dataset, split, run_name=run_name)
        out_path.write_text(json.dumps(result, indent=2))
        bf1 = result["metrics"]["boundary_f1"]["foreground_macro_mean"]
        dsc = result["metrics"]["dsc"]["foreground_macro_mean"]
        print(f"  WROTE {out_name}  DSC={dsc:.4f}  BF1={bf1:.4f}")


if __name__ == "__main__":
    main()
